# Generated by Django 4.0.1 on 2022-09-17 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0002_alter_banner_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='horse',
            name='description',
            field=models.TextField(default='This is an amazing horse.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='publication',
            name='description',
            field=models.TextField(default="Don't forget to add a Description!", max_length=1000),
        ),
    ]
