# Generated by Django 4.0.1 on 2022-10-31 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0003_horse_description_alter_publication_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horse',
            name='note',
            field=models.CharField(default='Make Horse Image 2000px By 2000px', editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='people',
            name='note',
            field=models.CharField(default='Make Image 2000px By 2000px', editable=False, max_length=100),
        ),
    ]
