# Generated by Django 4.1.3 on 2022-11-06 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0005_event_publication_date_alter_banner_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(default='Founder Rehab Ranch', max_length=300),
        ),
    ]
